import type { Metadata } from "next";
import { Inter, Exo_2 } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css';
import BootstrapClient from "@/components/BootstrapClient";
import BreadcrumbsComponent from "@/app/component/breadcrumbsComponent";

const inter = Inter({ subsets: ["latin"] });
const exo2 = Exo_2({ subsets: ["latin"], weight: "300", variable: "--font-exo2" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${exo2.variable} my-body`} data-bs-theme="dark">
        <BreadcrumbsComponent/>
        {children}
        <BootstrapClient />
      </body>
    </html>
  );
}
